In [1]:
# -----------01_STAT_ASS_02_(Python Notebook)--------------

In [2]:
import numpy as np
import pandas as pd
import scipy.stats
from scipy import stats

In [20]:
samples = np.random.normal(100, 15, 1000) # (mean, sd, values)
print(samples)

[ 93.19640495  98.72596624  68.61866041  95.90144223 127.3956596
  86.70151064  71.70580682  81.55223207  78.26107744 104.62467349
 108.45886103 103.81850917  74.05762044 115.98792963 125.32192713
 109.81205323  77.89735731 111.04854643 111.78074385  99.93051033
 119.8835638   90.76793789  83.16769099  79.60763122 112.87728316
 121.96683465 118.08193906  80.21238698  93.57025904  78.22794528
 117.52335061  86.49961495 129.48327576 119.79911196 111.09467643
 127.44260726  75.80775783 109.51665035 127.68136088 114.53309505
 101.13318253 104.71489234 105.47951457 119.29287347 115.6651638
 109.77367638  97.16884631 107.09484977 131.93181879  80.91918646
  83.29797455 128.92863926 123.8855145  114.22657903  99.19981862
  96.74727662  63.10497941  68.95448998 114.99623624  98.35107986
 129.21609619  97.14275901 102.5980646   73.2003876   97.51416562
  64.81389744  69.3884812   91.80389042 106.90182186 109.7948085
 105.19335542 117.69632317  89.26268051  80.30134724 100.6548127
  75.75199244 

In [4]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print("mean: ", mean)
print("median: ", median)
print("mode: ", mode)

mean:  99.84865749355218
median:  100.7081946889387
mode:  ModeResult(mode=array([42.01977773]), count=array([1]))


In [5]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3 - q1
print("min: ", min)
print("max: ", max)
print("q3: ", q3)
print("q1: ", q1)
print("iqr (q3-q1): ", iqr)

min:  42.019777729933075
max:  141.84647588401228
q3:  109.7408167455592
q1:  90.10017316948405
iqr (q3-q1):  19.64064357607515


In [6]:
variance = np.var(samples)
std_dev = np.std(samples)
print("variance: ", variance)
print("std_dev: ", std_dev)

variance:  219.3230801868372
std_dev:  14.809560431924952


In [7]:
skewness = stats.skew(samples) # (if "-" then left skew, "+" then right skew)
kurtosis = stats.kurtosis(samples)
print("skewness: ", skewness)
print("kurtosis: ", kurtosis)

skewness:  -0.22921638488673995
kurtosis:  0.16170569196331996


In [8]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [9]:
y = np.array([0,1,2,3,4,5,6,7,8,9])
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
r = np.corrcoef(x,y)
print(r)

[[1. 1.]
 [1. 1.]]


In [21]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(x)
print(y)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64


In [12]:
r = scipy.stats.pearsonr(x, y)
print(r)

(0.758640289091187, 0.010964341301680813)


In [13]:
rho = scipy.stats.spearmanr(x, y)
print("rho: ", rho)

rho:  SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)


In [14]:
import seaborn as sns

In [15]:
tips = sns.load_dataset("tips")

In [16]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [17]:
stats.pearsonr(tips['tip'], tips['total_bill'])[0]

0.6757341092113647