In [2]:
# -----------01_DAwPYTH_BP_01_(Numpy)--------------
# ----------------Numpy Arrays---------------------

In [ ]:
# SUMMARY

# http://www.numpy.org
import numpy as np
mylist = [1,2,3]
np.array(mylist)
np.arange(0,101,20)
np.linspace(0,5,21)
np.zeros((2,5))
np.ones((2,5))
np.eye(5) 
np.random.rand(2,3)
np.random.randint(0,101,10) 
np.random.seed(42)
np.random.rand(4) 
arr.shape
arr.reshape(5,5)
ranarr.max()
ranarr.min()
ranarr.argmax()
ranarr.argmin()
ranarr.dtype

In [3]:
# import numpy
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
type(mylist)

list

In [6]:
# numpy array
np.array(mylist)

array([1, 2, 3])

In [7]:
mylist

[1, 2, 3]

In [8]:
myarr = np.array(mylist)

In [9]:
myarr

array([1, 2, 3])

In [10]:
type(myarr)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [12]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
type(my_matrix)

list

In [14]:
np.array(my_matrix)  # 3 satır 3 sütun var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# Built in function veya built in def kullanacağız

In [60]:
# arange(start, stop, step)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [19]:
# zeros, ones....
# float number
np.zeros(5)  

array([0., 0., 0., 0., 0.])

In [20]:
# 2 satır, 5 sütun
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# np.linspace(start, stop, num)  # tam olarak 3 e bölünen yapacağız aşağıda 

In [24]:
# np.linspace(start, stop, num)
# arange ile karıştırma, orada step var burada num var, endpoint True default
# 0-10 arasını 3 e tam böl göster
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,11)  # buarada 0 dahil 10 dahil 11 numara var

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [27]:
# üstte 21 sayı yazılı
len(np.linspace(0,5,21))

21

In [28]:
# np.eye(axb)  a:satır b:sütun
# lineer algibra da kullanılıyor
np.eye(5)  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# np.random.rand(satır,sütun)
# her seferinde başka numara veriri
np.random.rand(1)

array([0.14608044])

In [30]:
# 0-1 arasında verir random her defasında değişik olur sayılar
np.random.rand(5,2)

array([[0.78122314, 0.23134071],
       [0.77859703, 0.02434509],
       [0.98636063, 0.04304949],
       [0.69823832, 0.4577528 ],
       [0.16925516, 0.38327286]])

In [31]:
np.random.rand(5,6)

array([[0.30830967, 0.00427379, 0.27477952, 0.08997657, 0.00303447,
        0.91446526],
       [0.82486713, 0.82994311, 0.61956458, 0.12057083, 0.45101335,
        0.45327068],
       [0.59365978, 0.76451297, 0.43905751, 0.32395623, 0.76056836,
        0.18074352],
       [0.90929268, 0.48221487, 0.5266028 , 0.59874095, 0.04889878,
        0.67881646],
       [0.81521245, 0.02372993, 0.64314742, 0.17672067, 0.29080701,
        0.29826189]])

In [32]:
np.random.rand(10)

array([0.48160211, 0.48605567, 0.35150144, 0.2853737 , 0.21762766,
       0.68429055, 0.67822343, 0.42518565, 0.02333396, 0.93837384])

In [33]:
np.random.rand(2,3)

array([[0.75154333, 0.66018669, 0.72713938],
       [0.93398662, 0.05993631, 0.00597534]])

In [34]:
# np.rand.randint(dahil,değil,adet)
# 0 dahil, 101 dahil değil, 5 tane random int ver
np.random.randint(0,101,5)

array([ 0, 34, 95, 83, 96])

In [35]:
# np.rand.randint(dahil,değil,axb kadar adet)
# 0 dahil, 101 dahil değil, 4 satır, 5 sütun 20 tane random int ver
np.random.randint(0,101,(4,5))

array([[ 6,  6, 72, 37, 25],
       [26, 95, 20, 43, 63],
       [97, 36, 23, 98, 60],
       [26,  1, 89,  8, 94]])

In [36]:
# 0 dahil 101 hariç 10 tane yaşı random int olarak ver
np.random.randint(0,101,10)  

array([ 4, 21, 44, 10, 61, 89, 21, 30, 65, 50])

In [37]:
# np.random.seed(sayı) hep aynı randomları ver
# 42 armstrong numberdır,
# başka bir sayıda kullanabilirsin,
# b seed kullandığında 4 random verilen sayılar hep aynı olacaktır.
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [65]:
# np.arange(start,stop)
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
# np.rearange(axb) listeyi veya arrayi axb lik bir arraye çevir
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
# ValueError: cannot reshape array of size 25 into shape (5,4)
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [68]:
# np.random.randint(start,stop,step)
ranarr = np.random.randint(0,101,10)
ranarr

array([87, 29, 37,  1, 63, 59, 20, 32, 75, 57])

In [69]:
# array.max()
ranarr.max()

87

In [70]:
# array.min()
ranarr.min()

1

In [71]:
# array.argmax()
ranarr.argmax()

0

In [72]:
# array.argmin()
ranarr.argmin()

3

In [73]:
# array.dtype
ranarr.dtype

dtype('int32')

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
# arr.shape
arr.shape

(25,)

In [76]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
arr.shape

(5, 5)

In [78]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [79]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
# http://www.numpy.org

In [54]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [55]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [80]:
import numpy as np
np.random.randint(1,10)

6

In [84]:
# Generate a 1 x 3 array with 3 different upper bounds
np.random.randint(1, [3, 5, 10])

array([2, 3, 3])

In [82]:
# Generate a 1 by 3 array with 3 different lower bounds
np.random.randint([1, 5, 7], 10)

array([1, 7, 9])

In [83]:
# Generate a 2 by 4 array using broadcasting with dtype of uint8
np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)

array([[ 7,  4,  8,  9],
       [12, 12, 15, 18]], dtype=uint8)

In [57]:
myarray = np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [58]:
len(np.linspace(0,10,101))

101