In [1]:
# -----------02_DAwPYTH_BP_02_(Numpy)--------------
# ----------Numpy Indexing and Slicing-------------

In [ ]:
# SUMMARY

arr = np.arange(0,11)
arr[0:5]
arr[0:5] = 100
arr.copy()
arr > 4
arr[arr > 4]
len(arr[arr > 4])
b[2::2,::2]

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy[:] = 100

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d.shape

(3, 3)

In [25]:
arr_2d[2]

array([35, 40, 45])

In [26]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[0][1]

10

In [28]:
arr_2d[0,1]

10

In [30]:
arr_2d[1,1:]

array([25, 30])

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [37]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
a = np.arange(0,36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [50]:
b = a.reshape(6,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
b[0,3:5]

array([3, 4])

In [52]:
b[4:,4:]

array([[28, 29],
       [34, 35]])

In [53]:
b[:,2]

array([ 2,  8, 14, 20, 26, 32])

In [54]:
b[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [4]:
dice_rolls = np.array([1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
type(dice_rolls)

<IPython.core.display.Javascript object>

numpy.ndarray

In [1]:
dice_rolls = np.array([1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
dice_rolls > 2

<IPython.core.display.Javascript object>

array([False,  True, False,  True, False, False,  True, False,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [2]:
dice_rolls = np.array([1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
dice_rolls[dice_rolls > 2]

<IPython.core.display.Javascript object>

array([5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [3]:
dice_rolls = np.array([1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = len(dice_rolls[dice_rolls > 2])
total_rolls_over_two

<IPython.core.display.Javascript object>

18

In [58]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[2:5]

array([2, 3, 4])

In [62]:
arr = np.arange(1,8)
arr[arr > 4]

array([5, 6, 7])

In [63]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [65]:
arr_2d[0,2]

15