In [1]:
# -----------03_DAwPYTH_BP_03_(Numpy)--------------
# ---------------Numpy Operation-------------------

In [ ]:
# SUMMARY

arr = np.arange(0,10)
arr2d = np.arange(0,25).reshape(5,5)
arr + 5
arr - 2
arr + arr
arr * arr
arr - arr
arr / arr
1 / arr 
np.sqrt(arr)
np.sin(arr)
np.log(arr) 
np.exp(arr)
arr.sum()
arr.mean()
arr.std()
arr.var()
arr.max()
arr.min()
arr2d.sum(axis=0) # sütun 
arr2d.sum(axis=1) # satır
np.sqrt(arr_1) - np.max(arr_2)
arr_1 - arr_2
arr_2 = arr_1 * 3
np.sqrt(arr_1) - arr_2

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [8]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# because of 0 first element is nan
arr / arr  

<ipython-input-11-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
# because of 0 first element is infinite
1 / arr 

<ipython-input-13-9376d406218d>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr # because of 0 first element is infinite


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
# because of 0 first element is infinite
np.log(arr) 

<ipython-input-17-b2d7ed8b7b70>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # because of 0 first element is infinite


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [35]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr.sum()

45

In [20]:
arr.mean()

4.5

In [21]:
arr.max()

9

In [22]:
arr.var()

8.25

In [23]:
arr.std()

2.8722813232690143

In [28]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr2d.shape

(5, 5)

In [30]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr2d.sum()

300

In [32]:
# sütunları kendi içinde topla
arr2d.sum(axis=0) 

array([50, 55, 60, 65, 70])

In [33]:
# satırları kendi içinde topla
arr2d.sum(axis=1)  

array([ 10,  35,  60,  85, 110])

In [1]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
type(account_transactions)

<IPython.core.display.Javascript object>

numpy.ndarray

In [34]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_total = account_transactions.sum()
account_total

2720

In [36]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [37]:
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [38]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [39]:
arr_2d[2,1]

40

In [40]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [46]:
arr_2d.shape

(3, 3)

In [41]:
arr_2d[:1,1:]

array([[10, 15]])

In [42]:
arr = np.arange(1,6)
arr[arr > 3]

array([4, 5])

In [43]:
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

27

In [44]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1) - arr_2

array([0., 0., 0., 0., 0.])

In [51]:
arr=np.arange(1,37)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [52]:
arr.shape

(36,)

In [48]:
arr_2d = np.array(([5,10,15],[20,25,30]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30]])

In [49]:
arr_2d.shape

(2, 3)