In [121]:
# -----------01_DAwPYT_BL_01--------------

In [122]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt

In [123]:
liste = [1,2,3,4,5,6,7,8,9]
a = np.array(liste)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [125]:
type(a)

numpy.ndarray

In [126]:
a.shape

(9,)

In [127]:
a[3]

4

In [128]:
a[2]=8

In [129]:
a

array([1, 2, 8, 4, 5, 6, 7, 8, 9])

In [130]:
b = np.array([[1,2,3], [6,7,8]])
b.shape

(2, 3)

In [131]:
b[1,1] = 0

In [132]:
b

array([[1, 2, 3],
       [6, 0, 8]])

In [133]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [134]:
c.shape

(3, 3)

In [135]:
print(c)
# 1=SATIR, 0=SÜTUN

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [136]:
c[1,1]

5

#### zeros() / ones() / full() / empty() / eye()

In [137]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [138]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [139]:
np.full((2,2),-1)

array([[-1, -1],
       [-1, -1]])

In [140]:
np.empty((3,4))

array([[1.09916085e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.86712697e+169, 4.19640833e+175,
        9.41110022e-047],
       [6.01036301e-067, 3.40796191e-057, 7.27311801e-043,
        7.12195885e-067]])

In [141]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### arange() / linspace() / random() / randint()

In [142]:
np.arange(5,60)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59])

In [143]:
np.arange(5,60,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [144]:
np.linspace(2,30,5)

array([ 2.,  9., 16., 23., 30.])

In [145]:
np.random.random((3,3))

array([[0.40739291, 0.57566663, 0.47535524],
       [0.24479766, 0.48651613, 0.87646104],
       [0.94894861, 0.11639942, 0.28705709]])

In [146]:
np.random.randint(5,10, size=(4,4))

array([[6, 8, 5, 5],
       [6, 6, 9, 6],
       [9, 5, 7, 8],
       [8, 7, 9, 6]])

In [147]:
z = np.random.randint(2,15, size=(5,3))

In [148]:
z.shape

(5, 3)

In [149]:
z = z.reshape(3,5)

In [150]:
z.shape

(3, 5)

.ravel()

In [151]:
z = z.ravel()
z

array([ 8,  5,  7,  3,  4, 11,  9,  8,  3,  9, 10,  8, 10,  9,  5])

#### aggregations

In [152]:
z.max()

11

In [153]:
z.min()

3

In [154]:
z.argmax()

5

In [155]:
z.argmin()

3

#### hstack() / vstack() / unstack()

In [156]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3],[7,9]])

In [157]:
a

array([[1, 2],
       [3, 4]])

In [158]:
b

array([[-1,  3],
       [ 7,  9]])

In [159]:
np.hstack((a,b))

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [160]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [161]:
dizi = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [162]:
dizi_1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
dizi_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

#### concatenate()

In [163]:
np.concatenate([dizi, dizi_1], axis=1)

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [164]:
np.concatenate([dizi, dizi_1], axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
array_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
array_1.shape

(3, 4)

In [48]:
array_1[:2,1:3]

array([[2, 3],
       [6, 7]])

In [49]:
array_2 = array_1.copy()
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
array_2[1,1] = -6
array_2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
array_2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

#### conditional selecting

In [52]:
m=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m.shape

(4, 3)

In [53]:
ikidenbuyuk = m>2
m[ikidenbuyuk]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
m[m>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### arithmetics

In [55]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [56]:
x

array([[1, 2],
       [3, 4]])

In [57]:
y

array([[5, 6],
       [7, 8]])

In [58]:
x+y

array([[ 6,  8],
       [10, 12]])

In [59]:
x-y

array([[-4, -4],
       [-4, -4]])

In [60]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [62]:
x*y

array([[ 5, 12],
       [21, 32]])

In [61]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [ ]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#### .dot()

In [63]:
np.dot(x,y) # x'in satırı ile y'nin sütununu çarp ve topla.

array([[19, 22],
       [43, 50]])

In [64]:
x@y # x'in satırı ile y'nin sütununu çarp ve topla.

array([[19, 22],
       [43, 50]])

#### square() / sqrt() / exp() / log()

In [67]:
x

array([[1, 2],
       [3, 4]])

In [68]:
x**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [69]:
x1 = np.square(x)
x1

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [70]:
np.sqrt(x1)

array([[1., 2.],
       [3., 4.]])

In [71]:
np.exp(3) # e üzeri 3

20.085536923187668

In [73]:
np.log10(100) # 10 üzeri 2 100 eder >>> sonuç 2

2.0

In [72]:
np.log(100)

4.605170185988092

In [74]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])
t

array([0.52359878, 1.57079633, 1.04719755])

#### sin()

In [75]:
np.sin(t)

array([0.5      , 1.       , 0.8660254])